### PR TITLE
Add possibility to set parameters for blueprint generation. See angelozerr/angular2-eclipse#41

### PR DESCRIPTION
**Pull request by Springrbua**
I added the possibility to set the different parameters when generating a new Angular Element/Blueprint using the Wizards.  
Following Paramters are supported:
**Class:**  
- _--spec_

**Component:**  
- _--flat_
- _--inline-template_
- _--inline-style_
- _--prefix_
- _--spec_
- _--view-encapsulation_
- _--change-detection_
- _--skip-import_
- _--export_

**Directive:**  
- _--flat_
- _--prefix_
- _--spec_
- _--skip-import_
- _--export_

**Module:**  
- _--spec_
- _--routing_

**Pipe:**  
- _--flat_
- _--spec_
- _--skip-import_
- _--export_

**Service:**

- _--flat_
- _--spec_  

The "--module" parameter is still missing (see #34 )

### CODE REVIEW

**Comment by Springrbua** [comment]
I changed the "skip npm" parameter to "skip install", to support latest angular-cli version.

**Comment by angelozerr** [comment]
Great job @Springrbua ! Many thanks!

**Comment by angelozerr** [comment]
@Springrbua perhaps we should add parameter name in the label like `Generate a file spec (--spec)`

What do you think?

**Comment by Springrbua** [comment]
You are right we should add that. I'll take a look at it, maybe I need to rearramge the params.

**Comment by angelozerr** [comment]
And perhaps add a better description for each param (same than ng help) with a tooltip?

**Comment by Springrbua** [comment]
Unfortunately "ng help" does only show the parameters, their default value and the aliases:
```
      class <name> <options...>
        --spec (Boolean)
          aliases: -spec
```  
The [docs](https://github.com/angular/angular-cli/tree/master/docs/documentation/generate) seem to have at least a little description of the parameters, we could add that.

**Comment by angelozerr** [comment]
> we could add that.

Yes!

**Comment by Springrbua** [comment]
We could also add the parameter name ("--spec" for example) inside the tooltip?

**Pull request merged**
