### PR TITLE
Replace project selection with folder selection.

### PR DESCRIPTION
**Pull request by Springrbua**
Closes angelozerr/angular2-eclipse#37

I replaced the project selection (Combobox) with folder selection (Textfield + "Browse"-Button).
The Angular-CLI command will then be executed inside the selected folder.
This does not mean, that the generated file(s)/folder(s) will be inside the selected folder, but the Angular-CLI will handle the selection correctly.
For example, if you select an invalid folder ("node_modules" for instance), the file(s)/folder(s) will be generated in "/src/app".

### CODE REVIEW

**Comment by angelozerr** [comment]
@Springrbua I think we should keep the project combo (commons usage) but set the combo as NOT_READONLY in order to set text like you have done.

What do you think about that?

**Comment by Springrbua** [comment]
@angelozerr Well, I don't think, that the project-selection is neccesary:  
If I look at the "New Java Class" wizard, there is a "Soruce folder" and a "Package", which are both automatically selected. They are Textfields with a browse-button and I actually never (or very rarely) needed to change them manually.  
Also I don't think, that you often need to generate something at project-level. The Applications entry-point ("app.module.ts" and "app.component.ts") are generated with the project. After that, I guess, you should split your application into sub-modules, so you need to select the sub-folder.  
If you really need to generate components at project-level, you can easily select the project, the "src"-folder or the "app"-Folder. The result will always be the same.  

But if you would like to keep the project-selection, I'll add the combo again.

**Comment by angelozerr** [comment]
> If I look at the "New Java Class" wizard, there is a "Soruce folder" and a "Package", which are both automatically selected. 

If it works like this, it's very cool. To be honnest with you I have not played with your wizard. The combo existed to select an agular cli project. With your wizard it seems that you don't check that project is an angular cli project

**Comment by Springrbua** [comment]
> The combo existed to select an agular cli project. With your wizard it seems that you don't check that project is an angular cli project

Thats right, I am using the default "ContainerSelectionDialog", which does not seem to support filtering.  
I noticed, that the Angular-CLI will give an error, if you are not inside an Angular-CLI project, so I thought thats enough for now. Of course, the support should be improved over time, and only valid folders (and projects) should be selectable.  
However, I think, this means to create a custom "SelectionDialog" and I don't know how to do that yet, so this will take some more time...  
However, we could at least add a validation for the moment. It shouldn't be to hard, to figure out, if the selected folder is inside an Angular-CLI project right?

**Comment by angelozerr** [comment]
@Springrbua you works is very cool, I wanted just to discuss with you. I accept your PR and we will improve it in the future. Thanks!

**Comment by Springrbua** [comment]
@angelozerr thanks a lot :)  
BTW: I'll E-Mail you shortly, cause I would like to have another communication channel, where we could discuss about the plugin. Is that okay for you?

**Comment by angelozerr** [comment]
Yes sure, send me a mail.

**Pull request merged**
